modLoader = "javafml"
loaderVersion = "[2,]"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    authors = "${mod_author}"
    description = '''${mod_description}'''
    logoFile = "icon.png"

[[mixins]]
    config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    required = true
    versionRange = "${neoforge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,)"
    ordering = "NONE"
    side = "BOTH"